name: ShellSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Zsh and set as default shell
      run: |
        sudo apt-get install -y zsh
        sudo chsh -s $(which zsh)

    - name: Install ShellSpec
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Create SSH test profile structure
      run: |
        mkdir -p ~/.ssh/contexts/test-profile
        touch ~/.ssh/contexts/test-profile/{config,id_rsa,id_rsa.pub,known_hosts}
        chmod 600 ~/.ssh/contexts/test-profile/id_rsa
        chmod 700 ~/.ssh/contexts ~/.ssh/contexts/test-profile

    - name: Run ShellSpec tests
      run: shellspec -s zsh