name: Run ShellSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Zsh
      run: sudo apt-get install -y zsh

    - name: Install ShellSpec
      run: |
        curl -fsSL https://git.io/shellspec | sh -s -- --yes
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run ShellSpec tests
      run: shellspec -s zsh